name: Clone and Push to Bitbucket

on:
  push:
    branches:
      - main

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "manthanjgodhasara160901@gmail.com"
          git config --global user.name "manthanjgodhasara"

      - name: Clone Bitbucket repository
        run: |
          git clone --branch master https://manthangodhasara@bitbucket.org/manthan-workspace1/selenium_grid_testing.git temp_clone
        env:
          BITBUCKET_AUTH: ${{ secrets.BITBUCKET_AUTH }}

      - name: Copy files to Bitbucket repository
        run: |
          cp -r * temp_clone
        working-directory: temp_clone

      - name: Commit and push changes to Bitbucket
        run: |
          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin master
        env:
          BITBUCKET_AUTH: ${{ secrets.BITBUCKET_AUTH }}

  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: rm -rf temp_clone
